ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER CNSS IDENTIFIED BY cnss';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 AND SQLCODE != -01921 THEN
      RAISE;
    END IF;
END;
/

GRANT CONNECT, RESOURCE TO CNSS;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO CNSS;

